### ISSUE TITLE
[Bug]: Freighter ship sensors console blue screen

### ISSUE THREAD

**Issue by tomekkiel** [Aurorastation/Aurora.3#17328]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

On the freighter shuttle ship, the sensors console displayed a blue screen, with the following errors:

TypeError: Unable to get property 'length' of undefined or null reference
   at u (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:611529)
   at t.Sensors (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:623623)
   at Te (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:174408)
   at Anonymous function (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:174676)
   at Be (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:174654)
   at Anonymous function (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:174596)
   at Be (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:174538)
   at je (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:181672)
   at We (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:181911)
   at Anonymous function (http://127.0.0.1:55023/tmp1632/tgui.bundle.js:1:725354)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"tomkiel","interface":"Sensors","window":{"key":"[0x202f76c]-main","size":null,"fancy":1,"locked":0}}

### How to reproduce

Unsure, I spawned in as the freighter captain.

### Round ID

cpL-aSRP

### Staff ckey

Melariara - was not able to solve the issue, was told to report it as a bug

**Comment by DreamySkrell** [comment]
cannot reproduce
