### ISSUE TITLE
[Bug]: Crew manifest exception

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#17615]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

The following occured when I was attempting to review the manifest at 16:36:00+ (server time) 15/10/2023 with the denoted round ID. I had not participated in the round and I joined the server at the end of it, just wanted to review the manifest anyway.

I put it as an issue because it usually resolves itself by re-opening the window, but this time it persisted until the true round end (the shift change was underway)

" at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/Aurorastation/Aurora.3. Thank you for your cooperation. 
 TypeError: Unable to get property 'toLowerCase' of undefined or null reference
   at Anonymous function (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:759257)
   at Anonymous function (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:41113)
   at map (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:90914)
   at Anonymous function (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:759027)
   at Anonymous function (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:41113)
   at map (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:90914)
   at t.ManifestSection (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:758873)
   at Be (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:174408)
   at Anonymous function (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:174676)
   at Te (http://127.0.0.1:41782/tmp8340/tgui.bundle.js:1:174654)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"nerdyvampire","interface":"CrewManifest","window":{"key":"[0x210000f1]-main","size":null,"fancy":1,"locked":0}}
"

### How to reproduce

I am not sure how to reproduce it.

### Round ID

cqi-bTf6

**Comment by sadkermit** [comment]
Happened again, affecting multiple people. Round ID this time was `cqB-daGV`.
